### ISSUE TITLE
Implement further "named" graphs

### ISSUE THREAD

**Issue by james-d-mitchell** [digraphs/Digraphs#383]
This issue is a feature request to implement a number of "named" graphs from the literature:

- [FolkmanGraph](https://en.wikipedia.org/wiki/Folkman_graph)
- TODO more

**Comment by james-d-mitchell** [comment]
@tomcontileslie discovered this: https://hog.grinvin.org/ViewGraphInfo.action and you can download the `g6` files.

**Comment by james-d-mitchell** [comment]
or https://hog.grinvin.org/MetaDirectory.action

**Comment by marinaanagno** [comment]
After @tomcontileslie discovered this website, we decided that the best way to go about solving the issue is to split the team into three groups where:
Group 1 will work on creating infrastructure for storing and retrieving graphs from their name and parameters (if applicable).
Group 2 will put the named graphs into the infrastructure.
Group 3 will create functions that generate graphs according to some parameters like in the `GeneralisedPetersenGraph` and `JohnsonDigraph` functions.

**Comment by tomcontileslie** [comment]
Just been looking around the HoG website to get an idea of the search functions and download options. I'm wondering whether we could create a Digraphs function called `GraphByHogId(int)` which, with internet enabled, goes and downloads the .g6 for the graph with the requested ID and converts it to a digraph. It could be a nice way of having a large bank of examples to hand - even graphs that don't have names. In any case, the direct link to download a HoG graph in g6 by its ID is:

https://hog.grinvin.org/DownloadGraphs.action?graphFormatName=Graph6&id=960

and you can replace the 960 at the end by the ID you want. Not every ID is actually linked to a graph, for some reason.

**Comment by reiniscirpons** [comment]
@tomcontileslie I personally dont think that having a function fetch the graph by ID from their website is the best approach:

- For one, someone would have to know exactly the ID of the graph they want to get from HoG, which means they would have to look it up at the HoG website anyway, which sort of undermines the point of having the function in the first place.
- Furthermore, this adds the HoG website as an external dependency, so we would need to monitor whether the site moves or goes down, or changes the URL for downloading the g6 etc. This can make the function unreliable and make tests/functions depending on it randomly fail if something happens to the website that we did not anticipate.
- Finally, I imagine that this method would be quite slow - certainly much slower than if we had all the graph g6 data available locally.

I think at the end of the meeting we agreed to instead to download the graph data and make a local database. Then using this database we follow exactly what @marinaanagno proposes in her comment. I would propose to narrow down the database by selecting the specific named graphs we want to use and then write some sort of code generation script to automate creating the functions and maybe tests.

Using exactly the approach you describe Tom, I made a scraper to download all of the existing graphs from HoG - both the g6 files and the name and properties listed on the website. Ive also found a [website](http://yaroslavvb.com/upload/graphs2.txt) hosting some of the mathematica GraphData graphs, and [another website](http://discretezoo.xyz) with a large graph database. This gives us 3 large data sources and Im now working on unifying all of them and filtering off the unnamed graphs (since we really only care about the named graphs). I then propose we manually pick the named graphs we want to include in the package and use some sort of code-generation thing to automate including them.

This approach would have the benefit of using the HoG data to automate the named graph creation, as you suggest, while also addressing my concerns since:

- By manually picking which named graphs we want in, the user can now just call them by the usual name, and doesnt need to look up any sort of ID.
- The graphs are stored locally so there are no external dependencies
- Fetching the graphs locally is much faster

**Comment by james-d-mitchell** [comment]
Thanks for your comments @tomcontileslie and @reiniscirpons, I think the approach that @reiniscirpons mentions is the one we should go for, for the reasons that @reiniscirpons mentions. We can discuss this some more on Wednesday though!

**Comment by wilfwilson** [comment]
Does anyone have any thoughts about how we should show which graphs are available? Equivalently, as a user, what do you think would be the most useful way of browsing/exploring which graphs are available?

One basic and easy option would be to have a chapter in the manual that just lists all of the available graphs.

Can anyone think of anything more sophisticated that would be better? Perhaps a function in GAP that lets you search for all available names beginning with/containing some substring?

**Comment by tomcontileslie** [comment]
@wilfwilson this is likely too complicated and tampers too much with the main GAP distribution, but I'll suggest it anyway just in case... GAP has autocompletion for functions - any way we could get it to suggest word completions if the prompt starts with the named graph command and you hit Tab? Something that'd look like e.g.
```
gap> D := NamedDigraph("Fo
FolkmanGraph
FooGraph
FooGraph2
```

**Comment by MTWhyte** [comment]
Earlier we discussed the format these arguments should take, and decided not to include the words "graph" or "digraph" in the arguments. For example, the FolkmanGraph would be created by `Digraph("Folkman")`, instead of `Digraph("FolkmanGraph")`.

I can't think of any mathematicians who have given their name to both a "graph" and a "digraph", but if Folkman was such a person we'd need the format `Digraph("FolkmanGraph")` and `Digraph("FolkmanDigraph")` to delineate. Hopefully this isn't actually a problem, but it's not impossible that it could come up.

**Comment by tomcontileslie** [comment]
@wilfwilson @james-d-mitchell @ChrisJefferson following the comments made last Wednesday, I've tried to see whether we can tweak the GAP tab-completion feature using only GAP code in the Digraphs package, with minimal destruction caused to the rest of GAP's features. Thanks to some pointers from you all, I've established that tab-completion is implemented in [`lib/cmdledit.g`](https://github.com/gap-system/gap/blob/master/lib/cmdledit.g), towards the end of the file.

If we wanted tab-completion for the database of named graphs, it would be fine to keep the implementation in the GAP system exactly as-is, but change the variable that stores all possible completions before filtering through them when the tab key is hit. In `cmdledit.g`, this variable appears in the implementation of [`GAPInfo.CommandLineEditFunctions.Functions.Completion`](https://github.com/gap-system/gap/blob/fcf3991b2bf8bb5aa8dcdedd62d14ef9fcd074a0/lib/cmdledit.g#L881). It is referred to as [`searchlist`](https://github.com/gap-system/gap/blob/fcf3991b2bf8bb5aa8dcdedd62d14ef9fcd074a0/lib/cmdledit.g#L980). It is set to some combination of `IDENTS_BOUND_GVARS()`, or `ALL_RNAMES()`, or `NamesOfComponents(some_record)` if completing a record component name.

Ideally, we'd like to add a case which gets triggered upon tab-completion **specifically** if the prompt is currently completing the string `Digraph("gjhjhg...`, and in this case we'd like to set the value of `searchlist` to be `NamesOfComponents(DIGRAPHS_NamedGraph6String)`. Completion would then work as normal, but it would have a set of candidates relevant to the string being written. Of course, the issue is that this code is in the main GAP distribution. Any solution we find which can be run from code in `pkg/Digraphs/...`, but which modifies the methods implemented in `cmdledit.g`, is likely to aggressively change system variables. I can imagine a future update to GAP which makes completion more flexible and allows packages to define custom lists triggered in specific cases, which we could port into nicely, but that's beyond the scope of what I was thinking of here.

The only other solution I see is tampering with the argument of `GAPInfo.CommandLineEditFunctions.Functions.Completion`, which is a list referred to as `l` with at least 6 elements, the third of which appears to be a string with the current contents of the prompt. However, I'm not sure where this completion function is called from, and suspect it might lie on the other side of the GAP kernel interface. [Chapter 10 of the GAP manual](https://www.gap-system.org/Manuals/doc/ref/chap10.html) may be relevant, I'm not sure.

Anyway, those are my thoughts after a little amount of time digging around, so I'll let people who know more than me let me know what they think!

_N.B. this whole hypothetical feature will only work if GAP has been compiled with [readline support](https://github.com/gap-system/gap/blob/master/INSTALL.md#readline)._

**Comment by ChrisJefferson** [comment]
So, I'm not totally convinced by this (although I'm happy to be convinced). I worry that auto-completing on Digraph(" is a bit specific -- if someone wanted to make their own function which took a digraph name and did something with it, they would not get autocomplete for example. Also, there is already some string-based autocompletion, if you press escape twice in a string, it tries to autocomplete it as a filename (this probably wouldn't conflict, just mentioning it).

If instead the named digraphs were all put in a record, and you wrote (for example) NamedDigraph.Wheel(6) (for example), then autocomplete would already work, as it works on members of records (I'm assuming here the record is a record of functions)

Is there a good reason to take a string, as opposed to storing in a record?

**Comment by tomcontileslie** [comment]
Thanks for your comments @ChrisJefferson, you make some really good points. It is true that creating an exception for this specific prompt prefix is likely to interfere with people doing similar things down the line. I think the appeal of having named digraphs called through `Digraph("folkman")` rather than `NamedDigraph.Folkman()` or `NamedDigraph.folkman` is two-fold:

- It's perhaps more natural to load a named graph using `Digraph("folkman")`, since this is the usual way of creating a Digraphs object, though this is mostly aesthetic
- We do currently have a record which will, for each graph name, have a g6 string assigned: this is the global variable `DIGRAPHS_NamedGraph6String`, but this is likely to have over a thousand keys, and the idea was to load the record into memory from a compressed file _only_ if `Digraphs("...")` is called at some point. That way, someone loading up Digraphs without the intention to use named graphs won't suffer from additional unpickling time. (It might be that unpickling takes negligible time anyway, I'm not sure - this may be a non-issue).

I was talking to @MTWhyte about this and initially wondered whether we should just define an accessible record which people can type and then use tab-completion on, as you suggest. Since this doesn't work without readline, I'm beginning to think it might make more sense to go for a more basic approach like the one floated by @wilfwilson: create a function e.g. `ListNamedGraphs` which gives you a list of all possible string completions:
```
gap> ListNamedGraphs("fo");
[ "folkman", "foobar" ]
```
Maybe this is a slightly less destructive method to implement for the time being!

**Comment by tomcontileslie** [comment]
### Todos for named "sporadic" graphs architecture
*All updates to be added to PR #404*

#### Implementation
- [X] Implement `Digraph(string)` method
- [X] Implement search function `ListNamedDigraphs(string)` (assigned: @tomcontileslie)

#### Testing
- [X] Implement extreme tests
- [ ] Implement standard tests (assigned: @tomcontileslie)

#### Documentation
- [ ] Create documentation for `Digraph(string)` and `ListNamedDigraphs(string)` (no-one assigned)
- [ ] Create guidelines for contributors wanting to add more graphs (assigned: @tomcontileslie)
- [ ] Create documentation for individual graphs in the database (assigned: @MTWhyte)

#### Database
- [ ] Add the actual database of named graphs (as a pickled record) (assigned: Group 2)
- [ ] Add the test database of named graphs (as a pickled record) (assigned: Group 2)

For that last point: I am in the process of writing the wiki page with contributing guidelines which will explain how to generate these databases!

**Comment by wilfwilson** [comment]
Thanks for working on this and keeping the issue up to date.

Just to note:

> I  [...] initially wondered whether we should just define an accessible record which people can type and then use tab-completion on, as you suggest. Since this doesn't work without readline...

I'm pretty sure that tab completing in GAP doesn't require readline (until about a month ago I wasn't using readline, and tab completion of global variables etc worked fine).
